In [2]:
import pandas as pd
import invest

In [5]:
# 주식 코드와 시작시간을 이용하여 데이터를 로드
input_code = 'AAPL'
input_time = '2020-01-01'

In [6]:
# 데이터 로드
df = invest.load_data(input_code, input_time)

In [7]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,71.721019,72.776598,71.466812,72.716072,135480400,0.0,0.0
2020-01-03 00:00:00-05:00,71.941305,72.771721,71.783939,72.009094,146322800,0.0,0.0
2020-01-06 00:00:00-05:00,71.127873,72.621654,70.876083,72.582916,118387200,0.0,0.0
2020-01-07 00:00:00-05:00,72.592609,72.849239,72.021246,72.241562,108872000,0.0,0.0
2020-01-08 00:00:00-05:00,71.943751,73.706271,71.943751,73.403641,132079200,0.0,0.0

In [8]:
# Invest라는 class 생성
invest_class = invest.Invest(df, _col = "Close", _start= input_time)

In [12]:
# 유저가 보낸 데이터 중 투자 방식
input_type = 'boll'

In [13]:
if input_type == 'bnh':
    result = invest_class.buyandhold()
elif input_type == 'boll':
    result = invest_class.bollinger()
elif input_type == 'mmt':
    result = invest_class.momentum()

매수일 : 2020-02-24 05:00:00, 매수가 : 72.36203002929688
매도일 : 2020-04-14 04:00:00, 매도가 : 69.6610107421875
수익율 : 0.9626735280088766
매수일 : 2020-10-30 04:00:00, 매수가 : 106.14926147460938
매도일 : 2020-12-02 05:00:00, 매도가 : 120.22220611572266
수익율 : 1.1325769435002568
매수일 : 2021-02-22 05:00:00, 매수가 : 123.25833129882812
매도일 : 2021-04-07 04:00:00, 매도가 : 125.11698150634766
수익율 : 1.015079306915274

c:\mysite\invest\__init__.py:82: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.9626735280088766' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[idx, 'rtn'] = rtn

매수일 : 2021-05-04 04:00:00, 매수가 : 125.06806945800781
매도일 : 2021-06-14 04:00:00, 매도가 : 127.85768127441406
수익율 : 1.0223047483541983
매수일 : 2021-09-20 04:00:00, 매수가 : 140.277099609375
매도일 : 2021-10-19 04:00:00, 매도가 : 145.9886474609375
수익율 : 1.0407161815254753
매수일 : 2022-01-19 05:00:00, 매수가 : 163.3712921142578
매도일 : 2022-03-24 04:00:00, 매도가 : 171.29443359375
수익율 : 1.0484977585532649
매수일 : 2022-04-26 04:00:00, 매수가 : 154.29983520507812
매도일 : 2022-07-21 04:00:00, 매도가 : 153.09751892089844
수익율 : 0.9922079224350324
매수일 : 2022-08-30 04:00:00, 매수가 : 156.8234405517578
매도일 : 2022-10-25 04:00:00, 매도가 : 150.3397216796875
수익율 : 0.9586559327530476
매수일 : 2022-12-15 05:00:00, 매수가 : 134.93116760253906
매도일 : 2023-01-23 05:00:00, 매도가 : 139.48818969726562
수익율 : 1.0337729390154689
매수일 : 2023-08-04 04:00:00, 매수가 : 180.42222595214844
매도일 : 2023-08-31 04:00:00, 매도가 : 186.50306701660156
수익율 : 1.0337033923196683
매수일 : 2023-10-26 04:00:00, 매수가 : 165.67572021484375
매도일 : 2023-11-10 05:00:00, 매도가 : 185.28756713867188
수익율 : 1.1183749006697905
매수일 : 2024-01-02 05:00:00, 매수가 : 184.53208923339844
매도일 : 2024-05-03 04:00:00, 매도가 : 182.51817321777344
수익율 : 0.9890863641982736
매수일 : 2024-08-05 04:00:00, 매수가 : 208.56903076171875
매도일 : 2024-09-30 04:00:00, 매도가 : 232.4883270263672
수익율 : 1.1146828758674878
매수일 : 2024-11-04 05:00:00, 매수가 : 221.52244567871094
매도일 : 2024-11-26 05:00:00, 매도가 : 234.8018341064453
수익율 : 1.059946017601279
매수일 : 2025-01-10 05:00:00, 매수가 : 236.58987426757812
투자기간 : 2020-01-01 00:00:00 ~ 2025-03-31 10:44:35.771932, 총 수익율 : 1.6400994040593586

In [16]:
result.tail()

,Close,center,up,down,trade,rtn,acc_rtn
Date,,,,,,,
2025-03-24 04:00:00,220.729996,226.7070,251.040841,202.373159,buy,1.0,1.640099
2025-03-25 04:00:00,223.750000,225.5425,247.930642,203.154359,buy,1.0,1.640099
2025-03-26 04:00:00,221.529999,224.6010,245.923835,203.278166,buy,1.0,1.640099
2025-03-27 04:00:00,223.850006,223.9285,244.396214,203.460786,buy,1.0,1.640099
2025-03-28 04:00:00,217.899994,222.7315,241.519905,203.943095,buy,1.0,1.640099